[package]
name = "souvlaki"
version = "0.6.1"
authors = ["Sinono3 <aldo@aael.xyz>"]
edition = "2018"
description = "A cross-platform media key and metadata handling library."
repository = "https://github.com/Sinono3/souvlaki"
documentation = "https://docs.rs/souvlaki"
license = "MIT"

[target.'cfg(target_os = "windows")'.dependencies.windows]
version = "0.48"
features = [
	"Foundation",
	"Media",
	"Win32_Foundation",
	"Win32_System_WinRT",
	"Storage_Streams",
]

[target.'cfg(target_os = "macos")'.dependencies]
block = "0.1.6"
cocoa = "0.24.0"
core-graphics = "0.22.2"
dispatch = "0.2.0"
objc = "0.2.7"

[target.'cfg(all(unix, not(target_os = "macos")))'.dependencies]
dbus = { version = "0.9.5", optional = true }
dbus-crossroads = { version = "0.5.0", optional = true }
zbus = { version = "3.9", optional = true }
zvariant = { version = "3.10", optional = true }
pollster = { version = "0.3", optional = true }

[features]
default = ["use_dbus"]
use_dbus = ["dbus", "dbus-crossroads"]
use_zbus = ["zbus", "zvariant", "pollster"]

[dev-dependencies]
winit = "0.28.0"
raw-window-handle = "0.5.0"

[target.'cfg(target_os = "windows")'.dev-dependencies.windows]
version = "0.48"
features = [
	"Win32_Foundation",
	"Win32_Graphics_Gdi",
	"Win32_System_LibraryLoader",
	"Win32_UI_WindowsAndMessaging"
]

[package.metadata.docs.rs]
default-target = "x86_64-unknown-linux-gnu"
targets = ["x86_64-apple-darwin", "x86_64-unknown-linux-gnu", "x86_64-pc-windows-msvc"]
