name: CI

on:
  push:
    branches: 
      - "**"
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        arch: [x86_64, aarch64]
        rust: [stable]
    env:
      target: >
        ${{ format('{0}-{1}', matrix.arch, fromJSON('{
          "ubuntu-latest": "unknown-linux-gnu",
          "macOS-latest": "apple-darwin",
          "windows-latest": "pc-windows-msvc"
          }')[matrix.os]) }}

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Install rust toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.rust }}
        targets: ${{ env.target }}

    - uses: Swatinem/rust-cache@v2

    - name: Run cargo build
      run: cargo build --release --target ${{ env.target }}
      if: ${{ runner.os != 'Linux' }}

    - name: Run cargo build (zbus)
      run: cargo build --release --all-targets --verbose --no-default-features --features=use_zbus
      if: ${{ runner.os == 'Linux' && matrix.arch == 'x86_64' }}

    - name: Run cross build
      run: |
        cargo install cross
        cross build --release --target ${{ env.target }}
      if: ${{ runner.os == 'Linux' }}
